BOOKS = {
    1: "Matthew",
    2: "Mark",
    3: "Luke",
    4: "John",
    5: "Acts",
    6: "Romans",
    7: "I Corinthians",
    8: "II Corinthians",
    9: "Galatians",
    10: "Ephesians",
    11: "Philippians",
    12: "Colossians",
    13: "I Thessalonians",
    14: "II Thessalonians",
    15: "I Timothy",
    16: "II Timothy",
    17: "Titus",
    18: "Philemon",
    19: "Hebrews",
    20: "James",
    21: "I Peter",
    22: "II Peter",
    23: "I John",
    24: "II John",
    25: "III John",
    26: "Jude",
    27: "Revelations",
}