//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _61_Mt_morphgnt {
            get {
                return ResourceManager.GetStream("_61_Mt_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _62_Mk_morphgnt {
            get {
                return ResourceManager.GetStream("_62_Mk_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _63_Lk_morphgnt {
            get {
                return ResourceManager.GetStream("_63_Lk_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _64_Jn_morphgnt {
            get {
                return ResourceManager.GetStream("_64_Jn_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _65_Ac_morphgnt {
            get {
                return ResourceManager.GetStream("_65_Ac_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _66_Ro_morphgnt {
            get {
                return ResourceManager.GetStream("_66_Ro_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _67_1Co_morphgnt {
            get {
                return ResourceManager.GetStream("_67_1Co_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _68_2Co_morphgnt {
            get {
                return ResourceManager.GetStream("_68_2Co_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _69_Ga_morphgnt {
            get {
                return ResourceManager.GetStream("_69_Ga_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _70_Eph_morphgnt {
            get {
                return ResourceManager.GetStream("_70_Eph_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _71_Php_morphgnt {
            get {
                return ResourceManager.GetStream("_71_Php_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _72_Col_morphgnt {
            get {
                return ResourceManager.GetStream("_72_Col_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _73_1Th_morphgnt {
            get {
                return ResourceManager.GetStream("_73_1Th_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _74_2Th_morphgnt {
            get {
                return ResourceManager.GetStream("_74_2Th_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _75_1Ti_morphgnt {
            get {
                return ResourceManager.GetStream("_75_1Ti_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _76_2Ti_morphgnt {
            get {
                return ResourceManager.GetStream("_76_2Ti_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _77_Tit_morphgnt {
            get {
                return ResourceManager.GetStream("_77_Tit_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _78_Phm_morphgnt {
            get {
                return ResourceManager.GetStream("_78_Phm_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _79_Heb_morphgnt {
            get {
                return ResourceManager.GetStream("_79_Heb_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _80_Jas_morphgnt {
            get {
                return ResourceManager.GetStream("_80_Jas_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _81_1Pe_morphgnt {
            get {
                return ResourceManager.GetStream("_81_1Pe_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _82_2Pe_morphgnt {
            get {
                return ResourceManager.GetStream("_82_2Pe_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _83_1Jn_morphgnt {
            get {
                return ResourceManager.GetStream("_83_1Jn_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _84_2Jn_morphgnt {
            get {
                return ResourceManager.GetStream("_84_2Jn_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _85_3Jn_morphgnt {
            get {
                return ResourceManager.GetStream("_85_3Jn_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _86_Jud_morphgnt {
            get {
                return ResourceManager.GetStream("_86_Jud_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream _87_Re_morphgnt {
            get {
                return ResourceManager.GetStream("_87_Re_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ἀαρών:
        ///    M:
        ///        NS:
        ///            forms:
        ///                -
        ///                    form: Ἀαρών
        ///        GS:
        ///            forms:
        ///                -
        ///                    form: Ἀαρών
        ///        DS:
        ///            forms:
        ///                -
        ///                    form: Ἀαρών
        ///Ἀβαδδών:
        ///    M:
        ///        NS:
        ///            forms:
        ///                -
        ///                    form: Ἀβαδδών
        ///ἀβαρής:
        ///    M:
        ///        AS:
        ///            forms:
        ///                -
        ///                    form: ἀβαρῆ
        ///αββα:
        ///    M:
        ///        VS:
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string forms {
            get {
                return ResourceManager.GetString("forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ἀαρών:
        ///    pos: N
        ///    full-citation-form: Ἀαρών, ὁ
        ///    bdag-headword: Ἀαρών
        ///    danker-entry: Ἀαρών, ὁ
        ///    dodson-entry: Ἀαρών, ὁ
        ///    mounce-headword: Ἀαρών
        ///    strongs: 2
        ///    gk: 2
        ///    dodson-pos: N-PRI
        ///    gloss: Aaron
        ///    mounce-morphcat: n-3g(2)
        ///Ἀβαδδών:
        ///    pos: N
        ///    full-citation-form: Ἀβαδδών, ὁ
        ///    bdag-headword: Ἀβαδδών
        ///    danker-entry: Ἀβαδδών, ὁ
        ///    dodson-entry: Ἀβαδδών, ὁ
        ///    mounce-headword: Ἀβαδδών
        ///    strongs: 3
        ///    gk: 3
        ///    dodson-pos: N-PRI
        ///    gloss: Abaddon
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lexemes {
            get {
                return ResourceManager.GetString("lexemes", resourceCulture);
            }
        }
    }
}
