//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibleCore.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BibleCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Α&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;1 Corinthians 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 Χριστοῦ Ἰησοῦ Treg NA28 ] Ἰησοῦ Χριστοῦ WH RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Corinthians 1:2&lt;/verse&gt;
        ///&lt;note&gt;2 ἡγιασμένοις ἐν Χριστῷ Ἰησοῦ τῇ οὔσῃ ἐν Κορίνθῳ Treg ] τῇ οὔσῃ ἐν Κορίνθῳ ἡγιασμένοις ἐν Χριστῷ Ἰησοῦ WH NA28 RP &lt;/note&gt;
        ///&lt;note&gt;• αὐτῶν WH Treg NA28 ] + τε RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Corinthians 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 μου Treg NA28 RP ] – WH&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Corinthians 1:14&lt;/verse&gt;
        ///&lt;note&gt;14 εὐχαριστῶ WH NIV ] + τῷ θεῷ Tr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1Cor {
            get {
                return ResourceManager.GetString("_1Cor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΙΩΑΝΝΟΥ Α&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;1 John 1:3&lt;/verse&gt;
        ///&lt;note&gt;1:3 καὶ WH Treg NA28 ] – RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 John 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 ἡμεῖς WH Treg NA28 ] ὑμῖν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 John 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 ἐν αὐτῷ οὐκ ἔστιν NA28 RP ] οὐκ ἔστιν ἐν αὐτῷ WH Treg&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 John 1:7&lt;/verse&gt;
        ///&lt;note&gt;7 δὲ WH Treg NA27 RP ] – NA28 &lt;/note&gt;
        ///&lt;note&gt;• Ἰησοῦ WH Treg NA28 ] + Χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 John 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 οὐκ ἔστιν ἐν ἡμῖν WH NA28 RP ] ἐν ἡμῖν οὐκ ἔστιν Treg&lt;/note&gt;
        ///
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1John {
            get {
                return ResourceManager.GetString("_1John", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΕΤΡΟΥ Α&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;1 Peter 1:6&lt;/verse&gt;
        ///&lt;note&gt;1:6 δέον WH Treg ] + ἐστίν NA28 RP &lt;/note&gt;
        ///&lt;note&gt;• λυπηθέντες WH Treg NA27 RP ] λυπηθέντας NA28&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Peter 1:7&lt;/verse&gt;
        ///&lt;note&gt;7 πολυτιμότερον WH Treg NA28 ] πολὺ τιμιώτερον RP &lt;/note&gt;
        ///&lt;note&gt;• δόξαν καὶ τιμὴν WH Treg NA28 ] τιμὴν καὶ εἰς δόξαν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Peter 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 ἰδόντες WH Treg NA28 ] εἰδότες RP &lt;/note&gt;
        ///&lt;note&gt;• ἀγαλλιᾶσθε Treg NA28 RP ] ἀγαλλιᾶτε WH&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Peter 1:9&lt;/verse&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1Pet {
            get {
                return ResourceManager.GetString("_1Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Α&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;1 Thessalonians 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 εἰρήνη WH Treg NA28 ] + ἀπὸ θεοῦ πατρὸς ἡμῶν καὶ κυρίου Ἰησοῦ Χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Thessalonians 1:2&lt;/verse&gt;
        ///&lt;note&gt;2 μνείαν WH Treg NA28 ] + ὑμῶν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Thessalonians 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 θεοῦ Treg RP ] τοῦ θεοῦ WH NA28&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Thessalonians 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 καὶ WH ] + ἐν Treg NA28 RP &lt;/note&gt;
        ///&lt;note&gt;• ἐν Treg NA28 RP ] – WH&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Thessalonians 1:7&lt;/verse&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1Thess {
            get {
                return ResourceManager.GetString("_1Thess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΤΙΜΟΘΕΟΝ Α&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;1 Timothy 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 Χριστοῦ Ἰησοῦ WH Treg NA28 ] Ἰησοῦ Χριστοῦ RP &lt;/note&gt;
        ///&lt;note&gt;• Χριστοῦ Ἰησοῦ WH Treg NA28 ] κυριόυ Ἰησοῦ Χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Timothy 1:2&lt;/verse&gt;
        ///&lt;note&gt;2 πατρὸς WH Treg NA28 ] + ἡμῶν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Timothy 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 ἐκζητήσεις WH Treg NA28 ] ζητήσεις RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Timothy 1:12&lt;/verse&gt;
        ///&lt;note&gt;12 Χάριν WH Treg NA28 ] Καὶ χάριν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;1 Timothy 1:13&lt;/verse&gt;
        ///&lt;note&gt;13 τὸ WH  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1Tim {
            get {
                return ResourceManager.GetString("_1Tim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΚΟΡΙΝΘΙΟΥΣ Β&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;2 Corinthians 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 Χριστοῦ Ἰησοῦ WH Treg NA28 ] Ἰησοῦ Χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Corinthians 1:6&lt;/verse&gt;
        ///&lt;note&gt;6 εἴτε παρακαλούμεθα, ὑπὲρ τῆς ὑμῶν παρακλήσεως WH NA28 ] – Treg RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Corinthians 1:7&lt;/verse&gt;
        ///&lt;note&gt;7 ὑμῶν WH NA28 ] + εἴτε παρακαλούμεθα, ὑπὲρ τῆς ὑμῶν παρακλήσεως καὶ σωτηρίας Treg RP &lt;/note&gt;
        ///&lt;note&gt;• ὡς WH Treg NA28 ] ὥσπερ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Corinthians 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 ὑπὲρ WH NA28 RP ] πε [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2Cor {
            get {
                return ResourceManager.GetString("_2Cor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΙΩΑΝΝΟΥ Β&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;2 John 1:3&lt;/verse&gt;
        ///&lt;note&gt;3 παρὰ WH Treg NA28 ] + κυρίου RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 John 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 καινὴν γράφων σοι Treg NA27 ] γράφων σοι καινὴν WH NA28 RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 John 1:6&lt;/verse&gt;
        ///&lt;note&gt;6 ἡ ἐντολή ἐστιν WH Treg NA28 ] ἐστιν ἡ ἐντολή RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 John 1:7&lt;/verse&gt;
        ///&lt;note&gt;7 ἐξῆλθον WH Treg NA28 ] εἰσῆλθόν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 John 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 ἀπολέσητε WH Treg NA28 ] ἀπολέσωμεν RP &lt;/note&gt;
        ///&lt;note&gt;• εἰργασάμεθα WH RP NA28  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2John {
            get {
                return ResourceManager.GetString("_2John", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΕΤΡΟΥ Β&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;2 Peter 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 Συμεὼν Treg NA28 RP ] Σιμων WH&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Peter 1:3&lt;/verse&gt;
        ///&lt;note&gt;3 ἰδίᾳ δόξῃ καὶ ἀρετῇ Treg NA28 ] διὰ δόξης καὶ ἀρετῆς WH RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Peter 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 τίμια καὶ μέγιστα ἡμῖν WH NA28 ] μέγιστα καὶ τίμια ἡμῖν Treg; τίμια ἡμῖν καὶ μέγιστα RP &lt;/note&gt;
        ///&lt;note&gt;• τῷ WH Treg NA28 ] – RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Peter 1:9&lt;/verse&gt;
        ///&lt;note&gt;9 ἁμαρτημάτων Treg ] ἁμαρτιῶν WH NA28 RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Peter 1:12&lt;/verse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2Pet {
            get {
                return ResourceManager.GetString("_2Pet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΘΕΣΣΑΛΟΝΙΚΕΙΣ Β&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;2 Thessalonians 1:2&lt;/verse&gt;
        ///&lt;note&gt;1:2 πατρὸς WH NIV ] + ἡμῶν Treg RP NA28&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Thessalonians 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 αὐτοὺς ἡμᾶς WH Treg NA28 ] ἡμᾶς αὐτοὺς RP &lt;/note&gt;
        ///&lt;note&gt;• ἐγκαυχᾶσθαι WH Treg NA28 ] καυχᾶσθαι RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Thessalonians 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 φλογὶ πυρός Treg ] πυρὶ φλογός WH NA28 RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Thessalonians 2:2&lt;/verse&gt;
        ///&lt;note&gt;2:2 μηδὲ WH Treg NA28 ] μήτε RP &lt;/note&gt;
        ///&lt;note&gt;• κυρίου WH Treg NA28 ] Χρι [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2Thess {
            get {
                return ResourceManager.GetString("_2Thess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΤΙΜΟΘΕΟΝ Β&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;2 Timothy 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 Χριστοῦ Ἰησοῦ WH Treg NA28 ] Ἰησοῦ Χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Timothy 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 λαβὼν WH Treg NA28 ] λαμβάνων RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Timothy 1:10&lt;/verse&gt;
        ///&lt;note&gt;10 Ἰησοῦ Χριστοῦ RP ] Χριστοῦ Ἰησοῦ WH Treg NA28&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Timothy 1:11&lt;/verse&gt;
        ///&lt;note&gt;11 διδάσκαλος WH NA28 ] + ἐθνῶν Treg RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 Timothy 1:17&lt;/verse&gt;
        ///&lt;note&gt;17 σπουδαίως WH Treg NA28 ] σπουδαιότερον RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;2 T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2Tim {
            get {
                return ResourceManager.GetString("_2Tim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΙΩΑΝΝΟΥ Γ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;3 John 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 χαράν Treg NA28 RP ] χάριν WH &lt;/note&gt;
        ///&lt;note&gt;• τῇ WH Treg NA27 ] – NA28 RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;3 John 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 τοῦτο WH Treg NA28 ] εἰς τοὺς RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;3 John 1:7&lt;/verse&gt;
        ///&lt;note&gt;7 ἐθνικῶν WH Treg NA28 ] ἐθνῶν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;3 John 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 ὑπολαμβάνειν WH Treg NA28 ] ἀπολαμβάνειν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;3 John 1:9&lt;/verse&gt;
        ///&lt;note&gt;9 τι WH Treg NA28 ] – RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;3 John 1:12&lt;/verse&gt;
        ///&lt;note&gt;12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3John {
            get {
                return ResourceManager.GetString("_3John", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 010101 N- ----NSF- Βίβλος Βίβλος βίβλος βίβλος
        ///010101 N- ----GSF- γενέσεως γενέσεως γενέσεως γένεσις
        ///010101 N- ----GSM- Ἰησοῦ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///010101 N- ----GSM- χριστοῦ χριστοῦ Χριστοῦ Χριστός
        ///010101 N- ----GSM- υἱοῦ υἱοῦ υἱοῦ υἱός
        ///010101 N- ----GSM- Δαυὶδ Δαυὶδ Δαυίδ Δαυίδ
        ///010101 N- ----GSM- υἱοῦ υἱοῦ υἱοῦ υἱός
        ///010101 N- ----GSM- Ἀβραάμ. Ἀβραάμ Ἀβραάμ Ἀβραάμ
        ///010102 N- ----NSM- Ἀβραὰμ Ἀβραὰμ Ἀβραάμ Ἀβραάμ
        ///010102 V- 3AAI-S-- ἐγέννησεν ἐγέννησεν ἐγέννησε(ν) γεννάω
        ///010102 RA ----ASM- τὸν τὸν τόν ὁ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _61_Mt_morphgnt {
            get {
                return ResourceManager.GetString("_61_Mt_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 020101 N- ----NSF- Ἀρχὴ Ἀρχὴ ἀρχή ἀρχή
        ///020101 RA ----GSN- τοῦ τοῦ τοῦ ὁ
        ///020101 N- ----GSN- εὐαγγελίου εὐαγγελίου εὐαγγελίου εὐαγγέλιον
        ///020101 N- ----GSM- Ἰησοῦ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///020101 N- ----GSM- ⸀χριστοῦ. χριστοῦ Χριστοῦ Χριστός
        ///020102 C- -------- ⸀Καθὼς Καθὼς καθώς καθώς
        ///020102 V- 3XPI-S-- γέγραπται γέγραπται γέγραπται γράφω
        ///020102 P- -------- ἐν ἐν ἐν ἐν
        ///020102 RA ----DSM- ⸂τῷ τῷ τῷ ὁ
        ///020102 N- ----DSM- Ἠσαΐᾳ Ἠσαΐᾳ Ἠσαΐᾳ Ἠσαΐας
        ///020102 RA ----DSM- τῷ τῷ τῷ ὁ
        ///020102 N- ----DSM- προφήτῃ⸃· προφή [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _62_Mk_morphgnt {
            get {
                return ResourceManager.GetString("_62_Mk_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 030101 C- -------- Ἐπειδήπερ Ἐπειδήπερ ἐπειδήπερ ἐπειδήπερ
        ///030101 A- ----NPM- πολλοὶ πολλοὶ πολλοί πολύς
        ///030101 V- 3AAI-P-- ἐπεχείρησαν ἐπεχείρησαν ἐπεχείρησαν ἐπιχειρέω
        ///030101 V- -AMN---- ἀνατάξασθαι ἀνατάξασθαι ἀνατάξασθαι ἀνατάσσομαι
        ///030101 N- ----ASF- διήγησιν διήγησιν διήγησιν διήγησις
        ///030101 P- -------- περὶ περὶ περί περί
        ///030101 RA ----GPN- τῶν τῶν τῶν ὁ
        ///030101 V- -XPPGPN- πεπληροφορημένων πεπληροφορημένων πεπληροφορημένων πληροφορέω
        ///030101 P- -------- ἐν ἐν ἐν ἐν
        ///030101 RP ----DP-- ἡμῖν ἡμῖ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _63_Lk_morphgnt {
            get {
                return ResourceManager.GetString("_63_Lk_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 040101 P- -------- Ἐν Ἐν ἐν ἐν
        ///040101 N- ----DSF- ἀρχῇ ἀρχῇ ἀρχῇ ἀρχή
        ///040101 V- 3IAI-S-- ἦν ἦν ἦν εἰμί
        ///040101 RA ----NSM- ὁ ὁ ὁ ὁ
        ///040101 N- ----NSM- λόγος, λόγος λόγος λόγος
        ///040101 C- -------- καὶ καὶ καί καί
        ///040101 RA ----NSM- ὁ ὁ ὁ ὁ
        ///040101 N- ----NSM- λόγος λόγος λόγος λόγος
        ///040101 V- 3IAI-S-- ἦν ἦν ἦν εἰμί
        ///040101 P- -------- πρὸς πρὸς πρός πρός
        ///040101 RA ----ASM- τὸν τὸν τόν ὁ
        ///040101 N- ----ASM- θεόν, θεόν θεόν θεός
        ///040101 C- -------- καὶ καὶ καί καί
        ///040101 N- ----NSM- θεὸς θεὸς θεός θεός
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _64_Jn_morphgnt {
            get {
                return ResourceManager.GetString("_64_Jn_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 050101 RA ----ASM- Τὸν Τὸν τόν ὁ
        ///050101 X- -------- μὲν μὲν μέν μέν
        ///050101 A- ----ASM- πρῶτον πρῶτον πρῶτον πρῶτος
        ///050101 N- ----ASM- λόγον λόγον λόγον λόγος
        ///050101 V- 1AMI-S-- ἐποιησάμην ἐποιησάμην ἐποιησάμην ποιέω
        ///050101 P- -------- περὶ περὶ περί περί
        ///050101 A- ----GPN- πάντων, πάντων πάντων πᾶς
        ///050101 I- -------- ὦ ὦ ὦ ὦ
        ///050101 N- ----VSM- Θεόφιλε, Θεόφιλε Θεόφιλε Θεόφιλος
        ///050101 RR ----GPN- ὧν ὧν ὧν ὅς
        ///050101 V- 3AMI-S-- ἤρξατο ἤρξατο ἤρξατο ἄρχω
        ///050101 RA ----NSM- ⸀ὁ ὁ ὁ ὁ
        ///050101 N- ----NS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _65_Ac_morphgnt {
            get {
                return ResourceManager.GetString("_65_Ac_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 060101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///060101 N- ----NSM- δοῦλος δοῦλος δοῦλος δοῦλος
        ///060101 N- ----GSM- ⸂Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///060101 N- ----GSM- Ἰησοῦ⸃, Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///060101 A- ----NSM- κλητὸς κλητὸς κλητός κλητός
        ///060101 N- ----NSM- ἀπόστολος, ἀπόστολος ἀπόστολος ἀπόστολος
        ///060101 V- -XPPNSM- ἀφωρισμένος ἀφωρισμένος ἀφωρισμένος ἀφορίζω
        ///060101 P- -------- εἰς εἰς εἰς εἰς
        ///060101 N- ----ASN- εὐαγγέλιον εὐαγγέλιον εὐαγγέλιον εὐαγγέλιον
        ///060101 N- ----GSM- θεοῦ θεοῦ θεοῦ θεός
        ///060 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _66_Ro_morphgnt {
            get {
                return ResourceManager.GetString("_66_Ro_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 070101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///070101 A- ----NSM- κλητὸς κλητὸς κλητός κλητός
        ///070101 N- ----NSM- ἀπόστολος ἀπόστολος ἀπόστολος ἀπόστολος
        ///070101 N- ----GSM- ⸂Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///070101 N- ----GSM- Ἰησοῦ⸃ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///070101 P- -------- διὰ διὰ διά διά
        ///070101 N- ----GSN- θελήματος θελήματος θελήματος θέλημα
        ///070101 N- ----GSM- θεοῦ θεοῦ θεοῦ θεός
        ///070101 C- -------- καὶ καὶ καί καί
        ///070101 N- ----NSM- Σωσθένης Σωσθένης Σωσθένης Σωσθένης
        ///070101 RA ----NSM- ὁ ὁ ὁ ὁ
        ///0701 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _67_1Co_morphgnt {
            get {
                return ResourceManager.GetString("_67_1Co_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 080101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///080101 N- ----NSM- ἀπόστολος ἀπόστολος ἀπόστολος ἀπόστολος
        ///080101 N- ----GSM- ⸂Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///080101 N- ----GSM- Ἰησοῦ⸃ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///080101 P- -------- διὰ διὰ διά διά
        ///080101 N- ----GSN- θελήματος θελήματος θελήματος θέλημα
        ///080101 N- ----GSM- θεοῦ θεοῦ θεοῦ θεός
        ///080101 C- -------- καὶ καὶ καί καί
        ///080101 N- ----NSM- Τιμόθεος Τιμόθεος Τιμόθεος Τιμόθεος
        ///080101 RA ----NSM- ὁ ὁ ὁ ὁ
        ///080101 N- ----NSM- ἀδελφὸς ἀδελφὸς ἀδελφός ἀδελφός
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _68_2Co_morphgnt {
            get {
                return ResourceManager.GetString("_68_2Co_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 090101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///090101 N- ----NSM- ἀπόστολος, ἀπόστολος ἀπόστολος ἀπόστολος
        ///090101 D- -------- οὐκ οὐκ οὐ οὐ
        ///090101 P- -------- ἀπ’ ἀπ’ ἀπό ἀπό
        ///090101 N- ----GPM- ἀνθρώπων ἀνθρώπων ἀνθρώπων ἄνθρωπος
        ///090101 C- -------- οὐδὲ οὐδὲ οὐδέ οὐδέ
        ///090101 P- -------- δι’ δι’ διά διά
        ///090101 N- ----GSM- ἀνθρώπου ἀνθρώπου ἀνθρώπου ἄνθρωπος
        ///090101 C- -------- ἀλλὰ ἀλλὰ ἀλλά ἀλλά
        ///090101 P- -------- διὰ διὰ διά διά
        ///090101 N- ----GSM- Ἰησοῦ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///090101 N- ----GSM- Χριστ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _69_Ga_morphgnt {
            get {
                return ResourceManager.GetString("_69_Ga_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///100101 N- ----NSM- ἀπόστολος ἀπόστολος ἀπόστολος ἀπόστολος
        ///100101 N- ----GSM- ⸂Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///100101 N- ----GSM- Ἰησοῦ⸃ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///100101 P- -------- διὰ διὰ διά διά
        ///100101 N- ----GSN- θελήματος θελήματος θελήματος θέλημα
        ///100101 N- ----GSM- θεοῦ θεοῦ θεοῦ θεός
        ///100101 RA ----DPM- τοῖς τοῖς τοῖς ὁ
        ///100101 A- ----DPM- ἁγίοις ἁγίοις ἁγίοις ἅγιος
        ///100101 RA ----DPM- τοῖς τοῖς τοῖς ὁ
        ///100101 V- -PAPDPM- οὖσιν οὖσιν οὖσι(ν) εἰμί
        ///100101 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _70_Eph_morphgnt {
            get {
                return ResourceManager.GetString("_70_Eph_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 110101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///110101 C- -------- καὶ καὶ καί καί
        ///110101 N- ----NSM- Τιμόθεος Τιμόθεος Τιμόθεος Τιμόθεος
        ///110101 N- ----NPM- δοῦλοι δοῦλοι δοῦλοι δοῦλος
        ///110101 N- ----GSM- ⸂Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///110101 N- ----GSM- Ἰησοῦ⸃ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///110101 A- ----DPM- πᾶσιν πᾶσιν πᾶσι(ν) πᾶς
        ///110101 RA ----DPM- τοῖς τοῖς τοῖς ὁ
        ///110101 A- ----DPM- ἁγίοις ἁγίοις ἁγίοις ἅγιος
        ///110101 P- -------- ἐν ἐν ἐν ἐν
        ///110101 N- ----DSM- Χριστῷ Χριστῷ Χριστῷ Χριστός
        ///110101 N- ----DS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _71_Php_morphgnt {
            get {
                return ResourceManager.GetString("_71_Php_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///120101 N- ----NSM- ἀπόστολος ἀπόστολος ἀπόστολος ἀπόστολος
        ///120101 N- ----GSM- ⸂Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///120101 N- ----GSM- Ἰησοῦ⸃ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///120101 P- -------- διὰ διὰ διά διά
        ///120101 N- ----GSN- θελήματος θελήματος θελήματος θέλημα
        ///120101 N- ----GSM- θεοῦ θεοῦ θεοῦ θεός
        ///120101 C- -------- καὶ καὶ καί καί
        ///120101 N- ----NSM- Τιμόθεος Τιμόθεος Τιμόθεος Τιμόθεος
        ///120101 RA ----NSM- ὁ ὁ ὁ ὁ
        ///120101 N- ----NSM- ἀδελφὸς ἀδελφὸς ἀδελφός ἀδελφός
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _72_Col_morphgnt {
            get {
                return ResourceManager.GetString("_72_Col_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 130101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///130101 C- -------- καὶ καὶ καί καί
        ///130101 N- ----NSM- Σιλουανὸς Σιλουανὸς Σιλουανός Σιλουανός
        ///130101 C- -------- καὶ καὶ καί καί
        ///130101 N- ----NSM- Τιμόθεος Τιμόθεος Τιμόθεος Τιμόθεος
        ///130101 RA ----DSF- τῇ τῇ τῇ ὁ
        ///130101 N- ----DSF- ἐκκλησίᾳ ἐκκλησίᾳ ἐκκλησίᾳ ἐκκλησία
        ///130101 N- ----GPM- Θεσσαλονικέων Θεσσαλονικέων Θεσσαλονικέων Θεσσαλονικεύς
        ///130101 P- -------- ἐν ἐν ἐν ἐν
        ///130101 N- ----DSM- θεῷ θεῷ θεῷ θεός
        ///130101 N- ----DSM- πατρὶ πατρὶ πατρί πατήρ
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _73_1Th_morphgnt {
            get {
                return ResourceManager.GetString("_73_1Th_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 140101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///140101 C- -------- καὶ καὶ καί καί
        ///140101 N- ----NSM- Σιλουανὸς Σιλουανὸς Σιλουανός Σιλουανός
        ///140101 C- -------- καὶ καὶ καί καί
        ///140101 N- ----NSM- Τιμόθεος Τιμόθεος Τιμόθεος Τιμόθεος
        ///140101 RA ----DSF- τῇ τῇ τῇ ὁ
        ///140101 N- ----DSF- ἐκκλησίᾳ ἐκκλησίᾳ ἐκκλησίᾳ ἐκκλησία
        ///140101 N- ----GPM- Θεσσαλονικέων Θεσσαλονικέων Θεσσαλονικέων Θεσσαλονικεύς
        ///140101 P- -------- ἐν ἐν ἐν ἐν
        ///140101 N- ----DSM- θεῷ θεῷ θεῷ θεός
        ///140101 N- ----DSM- πατρὶ πατρὶ πατρί πατήρ
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _74_2Th_morphgnt {
            get {
                return ResourceManager.GetString("_74_2Th_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 150101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///150101 N- ----NSM- ἀπόστολος ἀπόστολος ἀπόστολος ἀπόστολος
        ///150101 N- ----GSM- ⸂Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///150101 N- ----GSM- Ἰησοῦ⸃ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///150101 P- -------- κατ’ κατ’ κατά κατά
        ///150101 N- ----ASF- ἐπιταγὴν ἐπιταγὴν ἐπιταγήν ἐπιταγή
        ///150101 N- ----GSM- θεοῦ θεοῦ θεοῦ θεός
        ///150101 N- ----GSM- σωτῆρος σωτῆρος σωτῆρος σωτήρ
        ///150101 RP ----GP-- ἡμῶν ἡμῶν ἡμῶν ἐγώ
        ///150101 C- -------- καὶ καὶ καί καί
        ///150101 N- ----GSM- ⸂Χριστοῦ Χριστοῦ Χριστοῦ Χ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _75_1Ti_morphgnt {
            get {
                return ResourceManager.GetString("_75_1Ti_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 160101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///160101 N- ----NSM- ἀπόστολος ἀπόστολος ἀπόστολος ἀπόστολος
        ///160101 N- ----GSM- ⸂Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///160101 N- ----GSM- Ἰησοῦ⸃ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///160101 P- -------- διὰ διὰ διά διά
        ///160101 N- ----GSN- θελήματος θελήματος θελήματος θέλημα
        ///160101 N- ----GSM- θεοῦ θεοῦ θεοῦ θεός
        ///160101 P- -------- κατ’ κατ’ κατά κατά
        ///160101 N- ----ASF- ἐπαγγελίαν ἐπαγγελίαν ἐπαγγελίαν ἐπαγγελία
        ///160101 N- ----GSF- ζωῆς ζωῆς ζωῆς ζωή
        ///160101 RA ----GSF- τῆς τῆς τῆς [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _76_2Ti_morphgnt {
            get {
                return ResourceManager.GetString("_76_2Ti_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 170101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///170101 N- ----NSM- δοῦλος δοῦλος δοῦλος δοῦλος
        ///170101 N- ----GSM- θεοῦ, θεοῦ θεοῦ θεός
        ///170101 N- ----NSM- ἀπόστολος ἀπόστολος ἀπόστολος ἀπόστολος
        ///170101 C- -------- δὲ δὲ δέ δέ
        ///170101 N- ----GSM- Ἰησοῦ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///170101 N- ----GSM- Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///170101 P- -------- κατὰ κατὰ κατά κατά
        ///170101 N- ----ASF- πίστιν πίστιν πίστιν πίστις
        ///170101 A- ----GPM- ἐκλεκτῶν ἐκλεκτῶν ἐκλεκτῶν ἐκλεκτός
        ///170101 N- ----GSM- θεοῦ θεοῦ θεοῦ θεός
        ///17 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _77_Tit_morphgnt {
            get {
                return ResourceManager.GetString("_77_Tit_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180101 N- ----NSM- Παῦλος Παῦλος Παῦλος Παῦλος
        ///180101 N- ----NSM- δέσμιος δέσμιος δέσμιος δέσμιος
        ///180101 N- ----GSM- Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///180101 N- ----GSM- Ἰησοῦ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///180101 C- -------- καὶ καὶ καί καί
        ///180101 N- ----NSM- Τιμόθεος Τιμόθεος Τιμόθεος Τιμόθεος
        ///180101 RA ----NSM- ὁ ὁ ὁ ὁ
        ///180101 N- ----NSM- ἀδελφὸς ἀδελφὸς ἀδελφός ἀδελφός
        ///180101 N- ----DSM- Φιλήμονι Φιλήμονι Φιλήμονι Φιλήμων
        ///180101 RA ----DSM- τῷ τῷ τῷ ὁ
        ///180101 A- ----DSM- ἀγαπητῷ ἀγαπητῷ ἀγαπητῷ ἀγαπητός
        ///1801 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _78_Phm_morphgnt {
            get {
                return ResourceManager.GetString("_78_Phm_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 190101 D- -------- Πολυμερῶς Πολυμερῶς πολυμερῶς πολυμερῶς
        ///190101 C- -------- καὶ καὶ καί καί
        ///190101 D- -------- πολυτρόπως πολυτρόπως πολυτρόπως πολυτρόπως
        ///190101 D- -------- πάλαι πάλαι πάλαι πάλαι
        ///190101 RA ----NSM- ὁ ὁ ὁ ὁ
        ///190101 N- ----NSM- θεὸς θεὸς θεός θεός
        ///190101 V- -AAPNSM- λαλήσας λαλήσας λαλήσας λαλέω
        ///190101 RA ----DPM- τοῖς τοῖς τοῖς ὁ
        ///190101 N- ----DPM- πατράσιν πατράσιν πατράσι(ν) πατήρ
        ///190101 P- -------- ἐν ἐν ἐν ἐν
        ///190101 RA ----DPM- τοῖς τοῖς τοῖς ὁ
        ///190101 N- ----DPM- προφήταις  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _79_Heb_morphgnt {
            get {
                return ResourceManager.GetString("_79_Heb_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200101 N- ----NSM- Ἰάκωβος Ἰάκωβος Ἰάκωβος Ἰάκωβος
        ///200101 N- ----GSM- θεοῦ θεοῦ θεοῦ θεός
        ///200101 C- -------- καὶ καὶ καί καί
        ///200101 N- ----GSM- κυρίου κυρίου κυρίου κύριος
        ///200101 N- ----GSM- Ἰησοῦ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///200101 N- ----GSM- Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///200101 N- ----NSM- δοῦλος δοῦλος δοῦλος δοῦλος
        ///200101 RA ----DPF- ταῖς ταῖς ταῖς ὁ
        ///200101 A- ----DPF- δώδεκα δώδεκα δώδεκα δώδεκα
        ///200101 N- ----DPF- φυλαῖς φυλαῖς φυλαῖς φυλή
        ///200101 RA ----DPF- ταῖς ταῖς ταῖς ὁ
        ///200101 P- -------- ἐν ἐ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _80_Jas_morphgnt {
            get {
                return ResourceManager.GetString("_80_Jas_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 210101 N- ----NSM- Πέτρος Πέτρος Πέτρος Πέτρος
        ///210101 N- ----NSM- ἀπόστολος ἀπόστολος ἀπόστολος ἀπόστολος
        ///210101 N- ----GSM- Ἰησοῦ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///210101 N- ----GSM- Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///210101 A- ----DPM- ἐκλεκτοῖς ἐκλεκτοῖς ἐκλεκτοῖς ἐκλεκτός
        ///210101 A- ----DPM- παρεπιδήμοις παρεπιδήμοις παρεπιδήμοις παρεπίδημος
        ///210101 N- ----GSF- διασπορᾶς διασπορᾶς διασπορᾶς διασπορά
        ///210101 N- ----GSM- Πόντου, Πόντου Πόντου Πόντος
        ///210101 N- ----GSF- Γαλατίας, Γαλατίας Γαλατίας Γαλατία
        ///210101 N- --- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _81_1Pe_morphgnt {
            get {
                return ResourceManager.GetString("_81_1Pe_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 220101 N- ----NSM- ⸀Συμεὼν Συμεὼν Συμεών Συμεών
        ///220101 N- ----NSM- Πέτρος Πέτρος Πέτρος Πέτρος
        ///220101 N- ----NSM- δοῦλος δοῦλος δοῦλος δοῦλος
        ///220101 C- -------- καὶ καὶ καί καί
        ///220101 N- ----NSM- ἀπόστολος ἀπόστολος ἀπόστολος ἀπόστολος
        ///220101 N- ----GSM- Ἰησοῦ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///220101 N- ----GSM- Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///220101 RA ----DPM- τοῖς τοῖς τοῖς ὁ
        ///220101 A- ----ASF- ἰσότιμον ἰσότιμον ἰσότιμον ἰσότιμος
        ///220101 RP ----DP-- ἡμῖν ἡμῖν ἡμῖν ἐγώ
        ///220101 V- -AAPDPM- λαχοῦσιν λαχοῦσιν λαχοῦ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _82_2Pe_morphgnt {
            get {
                return ResourceManager.GetString("_82_2Pe_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 230101 RR ----NSN- Ὃ Ὃ ὅ ὅς
        ///230101 V- 3IAI-S-- ἦν ἦν ἦν εἰμί
        ///230101 P- -------- ἀπ’ ἀπ’ ἀπό ἀπό
        ///230101 N- ----GSF- ἀρχῆς, ἀρχῆς ἀρχῆς ἀρχή
        ///230101 RR ----ASN- ὃ ὃ ὅ ὅς
        ///230101 V- 1XAI-P-- ἀκηκόαμεν, ἀκηκόαμεν ἀκηκόαμεν ἀκούω
        ///230101 RR ----ASN- ὃ ὃ ὅ ὅς
        ///230101 V- 1XAI-P-- ἑωράκαμεν ἑωράκαμεν ἑωράκαμεν ὁράω
        ///230101 RA ----DPM- τοῖς τοῖς τοῖς ὁ
        ///230101 N- ----DPM- ὀφθαλμοῖς ὀφθαλμοῖς ὀφθαλμοῖς ὀφθαλμός
        ///230101 RP ----GP-- ἡμῶν, ἡμῶν ἡμῶν ἐγώ
        ///230101 RR ----ASN- ὃ ὃ ὅ ὅς
        ///230101 V- 1AMI-P-- ἐθεασάμεθα ἐθεα [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _83_1Jn_morphgnt {
            get {
                return ResourceManager.GetString("_83_1Jn_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 240101 RA ----NSM- Ὁ Ὁ ὁ ὁ
        ///240101 A- ----NSM- πρεσβύτερος πρεσβύτερος πρεσβύτερος πρεσβύτερος
        ///240101 A- ----DSF- ἐκλεκτῇ ἐκλεκτῇ ἐκλεκτῇ ἐκλεκτός
        ///240101 N- ----DSF- κυρίᾳ κυρίᾳ κυρίᾳ κυρία
        ///240101 C- -------- καὶ καὶ καί καί
        ///240101 RA ----DPN- τοῖς τοῖς τοῖς ὁ
        ///240101 N- ----DPN- τέκνοις τέκνοις τέκνοις τέκνον
        ///240101 RP ----GSF- αὐτῆς, αὐτῆς αὐτῆς αὐτός
        ///240101 RR ----APM- οὓς οὓς οὕς ὅς
        ///240101 RP ----NS-- ἐγὼ ἐγὼ ἐγώ ἐγώ
        ///240101 V- 1PAI-S-- ἀγαπῶ ἀγαπῶ ἀγαπῶ ἀγαπάω
        ///240101 P- -------- ἐν ἐν ἐν ἐν
        ///24 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _84_2Jn_morphgnt {
            get {
                return ResourceManager.GetString("_84_2Jn_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 250101 RA ----NSM- Ὁ Ὁ ὁ ὁ
        ///250101 A- ----NSM- πρεσβύτερος πρεσβύτερος πρεσβύτερος πρεσβύτερος
        ///250101 N- ----DSM- Γαΐῳ Γαΐῳ Γαΐῳ Γάϊος
        ///250101 RA ----DSM- τῷ τῷ τῷ ὁ
        ///250101 A- ----DSM- ἀγαπητῷ, ἀγαπητῷ ἀγαπητῷ ἀγαπητός
        ///250101 RR ----ASM- ὃν ὃν ὅν ὅς
        ///250101 RP ----NS-- ἐγὼ ἐγὼ ἐγώ ἐγώ
        ///250101 V- 1PAI-S-- ἀγαπῶ ἀγαπῶ ἀγαπῶ ἀγαπάω
        ///250101 P- -------- ἐν ἐν ἐν ἐν
        ///250101 N- ----DSF- ἀληθείᾳ. ἀληθείᾳ ἀληθείᾳ ἀλήθεια
        ///250102 A- ----VSM- Ἀγαπητέ, Ἀγαπητέ ἀγαπητέ ἀγαπητός
        ///250102 P- -------- περὶ περὶ περί περί [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _85_3Jn_morphgnt {
            get {
                return ResourceManager.GetString("_85_3Jn_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 260101 N- ----NSM- Ἰούδας Ἰούδας Ἰούδας Ἰούδας
        ///260101 N- ----GSM- Ἰησοῦ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///260101 N- ----GSM- Χριστοῦ Χριστοῦ Χριστοῦ Χριστός
        ///260101 N- ----NSM- δοῦλος, δοῦλος δοῦλος δοῦλος
        ///260101 N- ----NSM- ἀδελφὸς ἀδελφὸς ἀδελφός ἀδελφός
        ///260101 C- -------- δὲ δὲ δέ δέ
        ///260101 N- ----GSM- Ἰακώβου, Ἰακώβου Ἰακώβου Ἰάκωβος
        ///260101 RA ----DPM- τοῖς τοῖς τοῖς ὁ
        ///260101 P- -------- ἐν ἐν ἐν ἐν
        ///260101 N- ----DSM- θεῷ θεῷ θεῷ θεός
        ///260101 N- ----DSM- πατρὶ πατρὶ πατρί πατήρ
        ///260101 V- -XPPDPM- ⸀ἠγαπημένοις [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _86_Jud_morphgnt {
            get {
                return ResourceManager.GetString("_86_Jud_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 270101 N- ----NSF- Ἀποκάλυψις Ἀποκάλυψις ἀποκάλυψις ἀποκάλυψις
        ///270101 N- ----GSM- Ἰησοῦ Ἰησοῦ Ἰησοῦ Ἰησοῦς
        ///270101 N- ----GSM- Χριστοῦ, Χριστοῦ Χριστοῦ Χριστός
        ///270101 RR ----ASF- ἣν ἣν ἥν ὅς
        ///270101 V- 3AAI-S-- ἔδωκεν ἔδωκεν ἔδωκε(ν) δίδωμι
        ///270101 RP ----DSM- αὐτῷ αὐτῷ αὐτῷ αὐτός
        ///270101 RA ----NSM- ὁ ὁ ὁ ὁ
        ///270101 N- ----NSM- θεὸς θεὸς θεός θεός
        ///270101 V- -AAN---- δεῖξαι δεῖξαι δεῖξαι δείκνυμι
        ///270101 RA ----DPM- τοῖς τοῖς τοῖς ὁ
        ///270101 N- ----DPM- δούλοις δούλοις δούλοις δοῦλος
        ///270101 RP ----GSM- αὐ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _87_Re_morphgnt {
            get {
                return ResourceManager.GetString("_87_Re_morphgnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΑΞΕΙΣ ΑΠΟΣΤΟΛΩΝ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Acts 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 ὁ NA28 RP ] – WH Treg&lt;/note&gt;
        ///
        ///&lt;verse&gt;Acts 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 ἐν πνεύματι βαπτισθήσεσθε WH Treg NA28 ] βαπτισθήσεσθε ἐν πνεύματι RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Acts 1:6&lt;/verse&gt;
        ///&lt;note&gt;6 ἠρώτων WH Treg NA28 ] ἐπηρώτων RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Acts 1:7&lt;/verse&gt;
        ///&lt;note&gt;7 δὲ NA28 RP ] – WH Treg&lt;/note&gt;
        ///
        ///&lt;verse&gt;Acts 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 μου WH Treg NA28 ] μοι RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Acts 1:10&lt;/verse&gt;
        ///&lt;note&gt;10 ἐσθήσεσι λευκαῖς WH Treg NA28 ] ἐ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Acts {
            get {
                return ResourceManager.GetString("Acts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΚΟΛΟΣΣΑΕΙΣ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Colossians 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 Χριστοῦ Ἰησοῦ WH Treg NA28 ] Ἰησοῦ Χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Colossians 1:2&lt;/verse&gt;
        ///&lt;note&gt;2 Κολοσσαῖς WH NA28 ] Κολασσαῖς Treg RP &lt;/note&gt;
        ///&lt;note&gt;• ἡμῶν WH Treg NA28 ] + καὶ κυρίου Ἰησοῦ Χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Colossians 1:3&lt;/verse&gt;
        ///&lt;note&gt;3 θεῷ WH NA28 ] + καὶ Treg RP &lt;/note&gt;
        ///&lt;note&gt;• περὶ WH NA28 RP ] ὑπὲρ Treg&lt;/note&gt;
        ///
        ///&lt;verse&gt;Colossians 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 ἣν ἔχετε WH Treg NA28 ] τὴν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Co [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Col {
            get {
                return ResourceManager.GetString("Col", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΕΦΕΣΙΟΥΣ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Ephesians 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 Χριστοῦ Ἰησοῦ WH Treg NA28 ] Ἰησοῦ Χριστοῦ RP &lt;/note&gt;
        ///&lt;note&gt;• ἐν Ἐφέσῳ WH Treg NA28 RP ] – WHapp&lt;/note&gt;
        ///
        ///&lt;verse&gt;Ephesians 1:6&lt;/verse&gt;
        ///&lt;note&gt;6 ἧς WH Treg NA28 ] ἐν ᾗ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Ephesians 1:7&lt;/verse&gt;
        ///&lt;note&gt;7 τὸ πλοῦτος WH Treg NA28 ] τὸν πλοῦτον RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Ephesians 1:14&lt;/verse&gt;
        ///&lt;note&gt;14 ὅ WH NA28 ] ὅς Treg RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Ephesians 1:15&lt;/verse&gt;
        ///&lt;note&gt;15 ἀγάπην τὴν Treg NA28 RP ] – WH&lt;/note&gt;
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Eph {
            get {
                return ResourceManager.GetString("Eph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ἀαρών:
        ///    M:
        ///        NS:
        ///            forms:
        ///                -
        ///                    form: Ἀαρών
        ///        GS:
        ///            forms:
        ///                -
        ///                    form: Ἀαρών
        ///        DS:
        ///            forms:
        ///                -
        ///                    form: Ἀαρών
        ///Ἀβαδδών:
        ///    M:
        ///        NS:
        ///            forms:
        ///                -
        ///                    form: Ἀβαδδών
        ///ἀβαρής:
        ///    M:
        ///        AS:
        ///            forms:
        ///                -
        ///                    form: ἀβαρῆ
        ///αββα:
        ///    M:
        ///        VS:
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string forms {
            get {
                return ResourceManager.GetString("forms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΓΑΛΑΤΑΣ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Galatians 1:3&lt;/verse&gt;
        ///&lt;note&gt;1:3 καὶ κυρίου ἡμῶν Treg RP ] ἡμῶν καὶ κυρίου WH NA28&lt;/note&gt;
        ///
        ///&lt;verse&gt;Galatians 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 ὑπὲρ WH NA28 ] περὶ Treg RP &lt;/note&gt;
        ///&lt;note&gt;• αἰῶνος τοῦ ἐνεστῶτος WH Treg NA28 ] ἐνεστῶτος αἰῶνος RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Galatians 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 εὐαγγελίζηται Treg NA28 RP ] εὐαγγελίσηται WH &lt;/note&gt;
        ///&lt;note&gt;• ὑμῖν WH Treg RP NA28 ] – NIV&lt;/note&gt;
        ///
        ///&lt;verse&gt;Galatians 1:10&lt;/verse&gt;
        ///&lt;note&gt;10 εἰ WH Treg NA28 ] + γὰρ RP&lt;/note&gt;
        ///        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Gal {
            get {
                return ResourceManager.GetString("Gal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΕΒΡΑΙΟΥΣ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Hebrews 1:2&lt;/verse&gt;
        ///&lt;note&gt;1:2 ἐποίησεν τοὺς αἰῶνας WH Treg NA28 ] τοὺς αἰῶνας ἐποίησεν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Hebrews 1:3&lt;/verse&gt;
        ///&lt;note&gt;3 διʼ αὑτοῦ Holmes ] αὐτοῦ WH Treg NA28; αὐτοῦ διʼ ἑαυτοῦ RP &lt;/note&gt;
        ///&lt;note&gt;• τῶν ἁμαρτιῶν ποιησάμενος WH Treg NA28 ] ποιησάμενος τῶν ἁμαρτιῶν ἡμῶν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Hebrews 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 καὶ ἡ ῥάβδος τῆς εὐθύτητος WH Treg NA28 ] ῥάβδος εὐθύτητος ἡ RP &lt;/note&gt;
        ///&lt;note&gt;• σου Treg NA28 RP ] αὐτοῦ WH&lt;/note&gt;
        ///
        ///&lt;verse [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Heb {
            get {
                return ResourceManager.GetString("Heb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΙΑΚΩΒΟΥ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;James 1:5&lt;/verse&gt;
        ///&lt;note&gt;1:5 μὴ WH Treg NA28 ] οὐκ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;James 1:12&lt;/verse&gt;
        ///&lt;note&gt;12 ἐπηγγείλατο WH Treg NA28 ] + ὁ κύριος RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;James 1:19&lt;/verse&gt;
        ///&lt;note&gt;19 Ἴστε WH Treg NA28 ] Ὥστε RP &lt;/note&gt;
        ///&lt;note&gt;• δὲ WH Treg NA28 ] – RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;James 1:20&lt;/verse&gt;
        ///&lt;note&gt;20 οὐκ ἐργάζεται WH Treg NA27 ] οὐ κατεργάζεται NA28 RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;James 1:22&lt;/verse&gt;
        ///&lt;note&gt;22 ἀκροαταὶ μόνον WH Treg ] μόνον ἀκροαταὶ NA28 RP&lt;/note&gt;
        ///
        ///&lt;vers [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jas {
            get {
                return ResourceManager.GetString("Jas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΚΑΤΑ ΙΩΑΝΝΗΝ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;John 1:15&lt;/verse&gt;
        ///&lt;note&gt;1:15 ὃν εἶπον Treg NA28 RP ] ὁ εἰπών WH&lt;/note&gt;
        ///
        ///&lt;verse&gt;John 1:16&lt;/verse&gt;
        ///&lt;note&gt;16 ὅτι WH Treg NA28 ] Καὶ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;John 1:18&lt;/verse&gt;
        ///&lt;note&gt;18 μονογενὴς θεὸς WH Treg NA28 ] ὁ μονογενὴς υἱός RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;John 1:19&lt;/verse&gt;
        ///&lt;note&gt;19 ἀπέστειλαν NIV RP ] + πρὸς αὐτὸν WH Treg NA28&lt;/note&gt;
        ///
        ///&lt;verse&gt;John 1:20&lt;/verse&gt;
        ///&lt;note&gt;20 Ἐγὼ οὐκ εἰμὶ WH Treg NA28 ] Οὐκ εἰμὶ ἐγὼ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;John 1:21&lt;/verse&gt;
        ///&lt;note&gt;21 σὺ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string John {
            get {
                return ResourceManager.GetString("John", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΙΟΥΔΑ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Jude 1:1&lt;/verse&gt;
        ///&lt;note&gt;1 ἠγαπημένοις WH Treg NA28 ] ἠγίασμένοις RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Jude 1:3&lt;/verse&gt;
        ///&lt;note&gt;3 ἡμῶν WH Treg NA28 ] – RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Jude 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 δεσπότην WH Treg NA28 ] + θεόν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Jude 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 ὑμᾶς ἅπαξ NA28 RP ] ἅπαξ ὑμᾶς NIV; ἅπαξ WH Treg; ὑμᾶς NA27 &lt;/note&gt;
        ///&lt;note&gt;• πάντα WH Treg NA28 ] τοῦτο RP &lt;/note&gt;
        ///&lt;note&gt;• Ἰησοῦς NA28 ] κύριος WH Treg; ὁ κύριος NIV RP; ὁ κύριος ἅπαξ NA27&lt;/note&gt;
        ///
        ///&lt;verse&gt;Jud [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Jude {
            get {
                return ResourceManager.GetString("Jude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ἀαρών:
        ///    pos: N
        ///    full-citation-form: Ἀαρών, ὁ
        ///    bdag-headword: Ἀαρών
        ///    danker-entry: Ἀαρών, ὁ
        ///    dodson-entry: Ἀαρών, ὁ
        ///    mounce-headword: Ἀαρών
        ///    strongs: 2
        ///    gk: 2
        ///    dodson-pos: N-PRI
        ///    gloss: Aaron
        ///    mounce-morphcat: n-3g(2)
        ///Ἀβαδδών:
        ///    pos: N
        ///    full-citation-form: Ἀβαδδών, ὁ
        ///    bdag-headword: Ἀβαδδών
        ///    danker-entry: Ἀβαδδών, ὁ
        ///    dodson-entry: Ἀβαδδών, ὁ
        ///    mounce-headword: Ἀβαδδών
        ///    strongs: 3
        ///    gk: 3
        ///    dodson-pos: N-PRI
        ///    gloss: Abaddon
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lexemes {
            get {
                return ResourceManager.GetString("lexemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΚΑΤΑ ΛΟΥΚΑΝ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Luke 1:5&lt;/verse&gt;
        ///&lt;note&gt;1:5 Ἡρῴδου WH Treg NA28 ] + τοῦ RP &lt;/note&gt;
        ///&lt;note&gt;• καὶ WH Treg NA28 ] + ἡ RP &lt;/note&gt;
        ///&lt;note&gt;• αὐτῷ WH Treg NA28 ] αὐτοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Luke 1:6&lt;/verse&gt;
        ///&lt;note&gt;6 ἐναντίον WH Treg NA28 ] ἐνώπιον RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Luke 1:7&lt;/verse&gt;
        ///&lt;note&gt;7 ἦν ἡ Ἐλισάβετ WH Treg NA28 ] ἡ Ἐλισάβετ ἦν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Luke 1:14&lt;/verse&gt;
        ///&lt;note&gt;14 γενέσει WH Treg NA28 ] γεννήσει RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Luke 1:15&lt;/verse&gt;
        ///&lt;note&gt;15 τοῦ Treg NA28 RP ]  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Luke {
            get {
                return ResourceManager.GetString("Luke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΚΑΤΑ ΜΑΡΚΟΝ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Mark 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 χριστοῦ WH ] + υἱοῦ θεοῦ Treg NA28; υἱοῦ τοῦ θεοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Mark 1:2&lt;/verse&gt;
        ///&lt;note&gt;2 Καθὼς WH Treg NA28 ] Ὡς RP &lt;/note&gt;
        ///&lt;note&gt;• τῷ Ἠσαΐᾳ τῷ προφήτῃ WH Treg NA28 ] τοῖς προφήταις RP &lt;/note&gt;
        ///&lt;note&gt;•  Ἰδοὺ WH Treg NA28 ] + ἐγὼ RP &lt;/note&gt;
        ///&lt;note&gt;• σου WH Treg NA28 ] + ἔμπροσθέν σου RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Mark 1:4&lt;/verse&gt;
        ///&lt;note&gt;4 ὁ WH Treg NA28 ] – RP &lt;/note&gt;
        ///&lt;note&gt;• ἐρήμῳ WH ] + καὶ Treg NA28 RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Mark 1: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΚΑΤΑ ΜΑΘΘΑΙΟΝ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Matthew 1:5&lt;/verse&gt;
        ///&lt;note&gt;1:5 Βόες … Βόες WH NA28 ] Βοὸς … Βοὸς Treg; Βοὸζ … Βοὸζ RP &lt;/note&gt;
        ///&lt;note&gt;• Ἰωβὴδ … Ἰωβὴδ WH Treg NA28 ] Ὠβὴδ … Ὠβὴδ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Matthew 1:6&lt;/verse&gt;
        ///&lt;note&gt;6 δὲ WH Treg NA28 ] + ὁ βασιλεὺς RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Matthew 1:7&lt;/verse&gt;
        ///&lt;note&gt;7–8 Ἀσάφ Ἀσὰφ WH Treg NA28 ] Ἀσά Ἀσὰ NIV RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Matthew 1:10&lt;/verse&gt;
        ///&lt;note&gt;10 Ἀμώς Ἀμὼς WH Treg NA28 ] Ἀμών Ἀμὼν NIV RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Matthew 1:18&lt;/verse&gt;
        ///&lt;note&gt;18 Ἰησο [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Matt {
            get {
                return ResourceManager.GetString("Matt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11	4
        ///34	4
        ///297	4
        ///476	4
        ///693	4
        ///1133	4
        ///1210	4
        ///1253	4
        ///1518	4
        ///1609	4
        ///2274	4
        ///2437	4
        ///2536	4
        ///2779	4
        ///2840	4
        ///3180	4
        ///3364	4
        ///4263	4
        ///4377	4
        ///4397	4
        ///4460	4
        ///4737	4
        ///4879	4
        ///4981	4
        ///5889	4
        ///5986	4
        ///27	6
        ///257	6
        ///899	6
        ///993	6
        ///1254	6
        ///1877	6
        ///2240	6
        ///2789	6
        ///3814	6
        ///3836	6
        ///4022	6
        ///4024	6
        ///6052	6
        ///281	7
        ///794	7
        ///1142	7
        ///1650	7
        ///2026	7
        ///2295	7
        ///2652	7
        ///3261	7
        ///3306	7
        ///3590	7
        ///4041	7
        ///4047	7
        ///5148	7
        ///5626	7
        ///6063	7
        ///247	8
        ///608	8
        ///1328	8
        ///1639	8
        ///1666	8
        ///2465	8
        ///2498	8
        ///2505	8
        ///2671	8
        ///2722	8
        ///3306	8
        ///3306	8
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mounce {
            get {
                return ResourceManager.GetString("mounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΦΙΛΙΠΠΗΣΙΟΥΣ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Philippians 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 Χριστοῦ Ἰησοῦ WH Treg NA28 ] Ἰησοῦ Χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Philippians 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 τῆς WH Treg NA28 ] – RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Philippians 1:6&lt;/verse&gt;
        ///&lt;note&gt;6 Χριστοῦ Ἰησοῦ Treg NA28 RP ] Ἰησοῦ Χριστοῦ WH&lt;/note&gt;
        ///
        ///&lt;verse&gt;Philippians 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 μου WH Treg NA28 ] + ἐστιν RP &lt;/note&gt;
        ///&lt;note&gt;• Χριστοῦ Ἰησοῦ WH Treg NA28 ] Ἰησοῦ Χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Philippians 1:11&lt;/verse&gt;
        ///&lt;note&gt;11 καρπὸν  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phil {
            get {
                return ResourceManager.GetString("Phil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΦΙΛΗΜΟΝΑ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Philemon 1:2&lt;/verse&gt;
        ///&lt;note&gt;1:2 ἀδελφῇ WH Treg NA28 ] ἀγαπητῇ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Philemon 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 πρὸς NA28 RP ] εἰς WH Treg&lt;/note&gt;
        ///
        ///&lt;verse&gt;Philemon 1:6&lt;/verse&gt;
        ///&lt;note&gt;6 τοῦ WH NA28 RP ] – Treg &lt;/note&gt;
        ///&lt;note&gt;• Χριστόν WH Treg NA28 ] + Ἰησοῦν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Philemon 1:7&lt;/verse&gt;
        ///&lt;note&gt;7 χαρὰν WH Treg NA28 ] Χάριν RP &lt;/note&gt;
        ///&lt;note&gt;• πολλὴν ἔσχον WH Treg NA28 ] ἔχομεν πολλὴν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Philemon 1:9&lt;/verse&gt;
        ///&lt;note&gt;9 Χριστοῦ Ἰ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Phlm {
            get {
                return ResourceManager.GetString("Phlm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΑΠΟΚΑΛΥΨΙΣ ΙΩΑΝΝΟΥ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Revelation 1:4&lt;/verse&gt;
        ///&lt;note&gt;1:4 ἀπὸ WH Treg NA28 ] + θεοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Revelation 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 λύσαντι WH Treg NA28 ] λούσαντι RP &lt;/note&gt;
        ///&lt;note&gt;• ἐκ WH Treg NA28 ] ἀπὸ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Revelation 1:6&lt;/verse&gt;
        ///&lt;note&gt;6 τῶν αἰώνων Treg NA28 RP ] – WH&lt;/note&gt;
        ///
        ///&lt;verse&gt;Revelation 1:9&lt;/verse&gt;
        ///&lt;note&gt;9 συγκοινωνὸς WH Treg NA28 ] κοινωνὸς RP &lt;/note&gt;
        ///&lt;note&gt;• ἐν WH Treg NA28 ] + Χριστῷ RP &lt;/note&gt;
        ///&lt;note&gt;• καὶ WH Treg NA28 ] + διὰ RP &lt;/n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rev {
            get {
                return ResourceManager.GetString("Rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΡΩΜΑΙΟΥΣ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Romans 1:1&lt;/verse&gt;
        ///&lt;note&gt;1:1 Χριστοῦ Ἰησοῦ Treg NA28 ] Ἰησοῦ Χριστοῦ WH RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Romans 1:8&lt;/verse&gt;
        ///&lt;note&gt;8 περὶ WH Treg NA28 ] ὑπὲρ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Romans 1:16&lt;/verse&gt;
        ///&lt;note&gt;16 εὐαγγέλιον WH Treg NA28 ] + τοῦ χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Romans 1:19&lt;/verse&gt;
        ///&lt;note&gt;19 θεὸς γὰρ WH Treg NA28 ] γὰρ θεὸς RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Romans 1:24&lt;/verse&gt;
        ///&lt;note&gt;24 Διὸ WH Treg NA28 ] + καὶ RP &lt;/note&gt;
        ///&lt;note&gt;• αὐτοῖς WH Treg NA28 ] ἑαυτοῖς RP&lt;/note&gt;
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Rom {
            get {
                return ResourceManager.GetString("Rom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;book&gt;
        ///&lt;book-name&gt;ΠΡΟΣ ΤΙΤΟΝ&lt;/book-name&gt;
        ///
        ///&lt;verse&gt;Titus 1:4&lt;/verse&gt;
        ///&lt;note&gt;1:4 καὶ WH Treg NA28 ] ἔλεος RP &lt;/note&gt;
        ///&lt;note&gt;• Χριστοῦ Ἰησοῦ WH Treg NA28 ] κυρίου Ἰησοῦ χριστοῦ RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Titus 1:5&lt;/verse&gt;
        ///&lt;note&gt;5 ἀπέλιπόν Treg NA28 ] ἀπέλειπόν WH; κατέλιπόν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Titus 1:10&lt;/verse&gt;
        ///&lt;note&gt;10 καὶ RP NA28 ] – WH Treg NIV &lt;/note&gt;
        ///&lt;note&gt;• τῆς WH Treg NA28 ] – RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Titus 1:15&lt;/verse&gt;
        ///&lt;note&gt;15 πάντα WH Treg NA28 ] + μὲν RP&lt;/note&gt;
        ///
        ///&lt;verse&gt;Titus 2:3&lt;/verse&gt;
        ///&lt;note&gt;2:3 μηδὲ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Titus {
            get {
                return ResourceManager.GetString("Titus", resourceCulture);
            }
        }
    }
}
